name = "aave-v3-pool"
version = "<%= package.version %>"

[setting.marketId]
defaultValue = "Ethereum Aave Market"

[setting.owner]
defaultValue = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266" # Anvil's first address (Swap this out when deploying to a network)

[contract.ReserveConfiguration]
artifact = 'contracts/protocol/libraries/configuration/ReserveConfiguration.sol:ReserveConfiguration'

[contract.PoolLogic]
artifact = 'contracts/protocol/libraries/logic/PoolLogic.sol:PoolLogic'

[contract.ReserveLogic]
artifact = 'contracts/protocol/libraries/logic/ReserveLogic.sol:ReserveLogic'

[contract.EModeLogic]
artifact = 'contracts/protocol/libraries/logic/EModeLogic.sol:EModeLogic'

[contract.SupplyLogic]
artifact = 'contracts/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic'

[contract.BorrowLogic]
artifact = 'contracts/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic'

[contract.FlashLoanLogic]
artifact = 'contracts/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic'

libraries.BorrowLogic = "<%= contracts.BorrowLogic.address %>"

depends = ["contract.BorrowLogic"]

[contract.LiquidationLogic]
artifact = 'contracts/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic'

[contract.DataTypes]
artifact = 'contracts/protocol/libraries/types/DataTypes.sol:DataTypes'

[contract.BridgeLogic]
artifact = 'contracts/protocol/libraries/logic/BridgeLogic.sol:BridgeLogic'


[contract.PoolAddressesProvider]
artifact = "contracts/protocol/configuration/PoolAddressesProvider.sol:PoolAddressesProvider"
args = [
  "<%= settings.marketId %>", # string memory marketId
  "<%= settings.owner %>", # address owner
]

[contract.Pool]
artifact = "contracts/protocol/pool/Pool.sol:Pool"
args = ["<%= contracts.PoolAddressesProvider.address %>"]

libraries.BorrowLogic = "<%= contracts.BorrowLogic.address %>"
libraries.ReserveConfiguration = "<%= contracts.ReserveConfiguration %>"
libraries.PoolLogic = "<%= contracts.PoolLogic %>"
libraries.ReserveLogic = "<%= contracts.ReserveLogic %>"
libraries.EModeLogic = "<%= contracts.EModeLogic %>"
libraries.SupplyLogic = "<%= contracts.SupplyLogic %>"
libraries.FlashLoanLogic = "<%= contracts.FlashLoanLogic %>"
libraries.LiquidationLogic = "<%= contracts.LiquidationLogic %>"
libraries.DataTypes = "<%= contracts.DataTypes %>"
libraries.BridgeLogic = "<%= contracts.BridgeLogic %>"

depends = [
  "contract.PoolAddressesProvider", 
  "contract.ReserveConfiguration",
  "contract.PoolLogic",
  "contract.ReserveLogic",
  "contract.EModeLogic",
  "contract.SupplyLogic",
  "contract.FlashLoanLogic",
  "contract.LiquidationLogic",
  "contract.DataTypes",
  "contract.BridgeLogic",

]
