name = "aave-v3-tokens"
version = "<%= package.version %>"
description = "Aave's v3 Various Token contracts"

[import.pool]
source = 'aave-v3-pool'

[contract.AToken]
artifact = "contracts/protocol/tokenization/AToken.sol:AToken"
args = [
  "<%= imports.pool.contracts.Pool.address %>"
]
depends = ["import.pool"]

[contract.StableDebtToken]
artifact = "contracts/protocol/tokenization/StableDebtToken.sol:StableDebtToken"
args = [
  "<%= imports.pool.contracts.Pool.address %>"
]
depends = ["import.pool"]

[contract.VariableDebtToken]
artifact = "contracts/protocol/tokenization/VariableDebtToken.sol:VariableDebtToken"
args = [
  "<%= imports.pool.contracts.Pool.address %>"
]
depends = ["import.pool"]